using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using Dapper;
using Mkb.DapperRepo.Repo;
using Mkb.DapperRepo.Tests.Entities;
using MySql.Data.MySqlClient;

namespace Mkb.DapperRepo.Tests.Utils
{
    public static class DataBaseScriptRunnerAndBuilder
    {
        public static void InsertTableWithNoAutoGeneratedPrimaryKey(string connection,
            IEnumerable<TableWithNoAutoGeneratedPrimaryKey> testTables)
        {
            var sql =
                $"Insert into {nameof(TableWithNoAutoGeneratedPrimaryKey)} (id,name,SomeNumber) values{string.Join(",", testTables.Select(f => $"('{f.Id}','{f.Name}',{f.SomeNumber})"))}";
            ExecuteCommandNonQuery(connection, sql);
        }

        public static void InsertTableWithAutoGeneratedPrimaryKey(string connection,
            IEnumerable<TableWithAutoIncrementPrimaryKey> testTables)
        {
            var sql =
                $"Insert into {nameof(TableWithAutoIncrementPrimaryKey)} (name,SomeNumber) values{string.Join(",", testTables.Select(f => $"('{f.Name}',{f.SomeNumber})"))}";
            ExecuteCommandNonQuery(connection, sql);
        }

        public static void RunDb(string connectionToMaster, string dbName, string scriptLocation)
        {
            var sql = File.ReadAllText(scriptLocation).Replace("PlaceHolderDbName", dbName);
            foreach (var item in sql.Split("{WaitBlock}"))
            {
                // this might be come a bottlekneck as we create a new connection for every command but hay its tests should not be doing anything massive
                ExecuteCommandNonQuery(connectionToMaster, item);
            }
        }

        public static void KillDb(string connectionToMaster, string dbName)
        {
            string start = Connection.SelectedEnvironment == Enviroment.Sql
                ? $"ALTER DATABASE [{dbName}] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE"
                : "";
            ExecuteCommandNonQuery(connectionToMaster, $"{start}{Environment.NewLine}DROP DATABASE {dbName}");
        }

        private static void ExecuteCommandNonQuery(string connection, string sql)
        {
            using var conn = GetConnection(connection);
            conn.Open();
            conn.Execute(sql);
        }

        public static DbConnection GetConnection(string connection)
        {
            switch (DapperRepo.Tests.Connection.SelectedEnvironment)
            {
                case Enviroment.MySql:
                    return new MySqlConnection(connection);
                case Enviroment.Sql:
                default:
                    return new SqlConnection(connection);
            }
        }

        public static IEnumerable<T> GetAll<T>(string connection) where T : class, new()
        {
            using var conn = GetConnection(connection);
            conn.Open();
            var items =   conn.Query<T>($"select * from {typeof(T).Name}");
            return items;
        }
    }
}