using System;
using System.Linq;
using System.Threading.Tasks;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using Xunit;

namespace Mkb.DapperRepo.Tests.Tests.Repo.GetAll
{
    [Collection("Integration")]
    public class GetAllAsyncTests : BaseAsyncTestClass
    {
        [Fact]
        public async Task Ensure_we_get_all_records_back()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33},
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1}
            };
            
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);
            
            var items = (await Sut.GetAll<TableWithNoAutoGeneratedPrimaryKey>()).ToArray();

            Assert.Equal(testTableItems.Length, items.Length);
            foreach (var item in testTableItems)
            {
                var test = items.FirstOrDefault(x => x.Id == item.Id);

                Assert.NotNull(test);
                Assert.Equal(item.NameTest, test.NameTest);
                Assert.Equal(item.SomeNumber, test.SomeNumber);
            }
        }
        
        [Fact]
        public async Task Ensure_we_get_all_records_back_with_diff_name()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33},
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1}
            };
            
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);
            
            var items = (await Sut.GetAll<TableWithNoAutoGeneratedPrimaryKeyDiffSqlName>()).ToArray();

            Assert.Equal(testTableItems.Length, items.Length);
            foreach (var item in testTableItems)
            {
                var test = items.FirstOrDefault(x => x.Id == item.Id);

                Assert.NotNull(test);
                Assert.Equal(item.NameTest, test.Name);
                Assert.Equal(item.SomeNumber, test.SomeNumber);
            }
        }
        
        [Fact]
        public async Task Ensure_if_we_have_no_records_we_do_not_blow_up()
        {
            var items = (await Sut.GetAll<TableWithNoAutoGeneratedPrimaryKey>()).ToArray();
            Assert.Empty(items);
        }
    }
}