using System;
using System.Linq;
using System.Threading.Tasks;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using Xunit;

namespace Mkb.DapperRepo.Tests.Tests.Repo.Count;

[Collection("Integration")]
public class CountAsyncTests : BaseAsyncTestClass
{
    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    public async Task Ensure_we_get_all_records_back(int length)
    {
        var testTableItems = Enumerable.Range(0, length).Select(w =>
                new TableWithNoAutoGeneratedPrimaryKey
                {
                    SomeNumber = w, Id = Guid.NewGuid().ToString("N"),
                    NameTest = Guid.NewGuid().ToString().Substring(0, 7)
                })
            .ToArray();

        DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

        var count = await Sut.Count<TableWithNoAutoGeneratedPrimaryKey>();

        Assert.Equal(testTableItems.Length, count);
    }

    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    public async Task Ensure_we_get_all_records_back_with_diff_name(int length)
    {
        var testTableItems = Enumerable.Range(0, length)
            .Select(w => new TableWithNoAutoGeneratedPrimaryKey
            {
                Id = Guid.NewGuid().ToString("N"),
                NameTest = Guid.NewGuid().ToString().Substring(0, 7),
                SomeNumber = w
            }).ToArray();

        DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

        var count = await Sut.Count<TableWithNoAutoGeneratedPrimaryKey>();

        Assert.Equal(testTableItems.Length, count);
    }

    [Fact]
    public async Task Ensure_if_we_have_no_records_we_do_not_blow_up()
    {
        var count = await Sut.Count<TableWithNoAutoGeneratedPrimaryKey>();
        Assert.Equal(0, count);
    }
}