using System;
using System.Linq;
using System.Threading.Tasks;
using DapperRepoTests.Entities;
using DapperRepoTests.Tests.BaseTestClasses;
using DapperRepoTests.Tests.QueryMany;
using DapperRepoTests.Utils;
using NUnit.Framework;

namespace DapperRepoTests.Tests.GetAll
{
    public class GetAllAsyncTests : BaseAsyncTestClass
    {
        public GetAllAsyncTests() : base( $"{nameof(QueryManyAsyncTests)}{RandomChars}")
        {
        }
        
        [Test]
        public async Task Ensure_we_get_all_records_back()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid(), Name = "Michale", SomeNumber = 33},
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid(), Name = "othername", SomeNumber = 1}
            };
            
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);
            
            var items = (await Sut.GetAll<TableWithNoAutoGeneratedPrimaryKey>()).ToArray();

            Assert.AreEqual(testTableItems.Length, items.Length);
            foreach (var item in testTableItems)
            {
                var test = items.FirstOrDefault(x => x.Id == item.Id);

                Assert.IsNotNull(test);
                Assert.AreEqual(item.Name, test.Name);
                Assert.AreEqual(item.SomeNumber, test.SomeNumber);
            }
        }
        
        [Test]
        public async Task Ensure_if_we_have_no_records_we_do_not_blow_up()
        {
            var items = (await Sut.GetAll<TableWithNoAutoGeneratedPrimaryKey>()).ToArray();
            Assert.AreEqual(0, items.Length);
        }
    }
}