using System;
using System.Linq;
using System.Threading.Tasks;
using Mkb.DapperRepo.Search;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using Xunit;

namespace Mkb.DapperRepo.Tests.Tests.Repo.Search
{
    [Collection("Integration")]
    public class SearchTermAsyncTests : BaseAsyncTestClass
    {
        [Fact]
        public async Task Single_equals_term_returns_matching_rows()
        {
            var items = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Alice", SomeNumber = 1 },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Bob",   SomeNumber = 2 },
            };
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, items);

            var result = await Sut.Search(new[]
            {
                SearchTerm<TableWithNoAutoGeneratedPrimaryKey>.Create(x => x.NameTest, "Alice", SearchType.Equals)
            });

            Assert.Single(result);
            Assert.Equal("Alice", result.First().NameTest);
        }

        [Fact]
        public async Task Multiple_terms_are_ANDed_together()
        {
            var goodId = Guid.NewGuid().ToString("N");
            var items = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey { Id = goodId,                       NameTest = "Alice", SomeNumber = 10 },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Alice", SomeNumber = 99 },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Bob",   SomeNumber = 10 },
            };
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, items);

            var result = await Sut.Search(new[]
            {
                SearchTerm<TableWithNoAutoGeneratedPrimaryKey>.Create(x => x.NameTest,   "Alice", SearchType.Equals),
                SearchTerm<TableWithNoAutoGeneratedPrimaryKey>.Create(x => x.SomeNumber, 10,      SearchType.Equals),
            });

            Assert.Single(result);
            Assert.Equal(goodId, result.First().Id);
        }

        [Fact]
        public async Task Range_query_works_by_using_same_property_twice()
        {
            var items = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "a", SomeNumber = 5  },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "b", SomeNumber = 15 },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "c", SomeNumber = 25 },
            };
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, items);

            var result = await Sut.Search(new[]
            {
                SearchTerm<TableWithNoAutoGeneratedPrimaryKey>.Create(x => x.SomeNumber, 10, SearchType.GreaterThan),
                SearchTerm<TableWithNoAutoGeneratedPrimaryKey>.Create(x => x.SomeNumber, 20, SearchType.LessThan),
            });

            Assert.Single(result);
            Assert.Equal(15, result.First().SomeNumber);
        }

        [Fact]
        public async Task IsNull_term_matches_null_values()
        {
            var goodId = Guid.NewGuid().ToString("N");
            var items = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey { Id = goodId,                       NameTest = "Alice", SomeNumber = null },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Bob",   SomeNumber = 5    },
            };
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, items);

            var result = await Sut.Search(new[]
            {
                SearchTerm<TableWithNoAutoGeneratedPrimaryKey>.IsNull(x => x.SomeNumber)
            });

            Assert.Single(result);
            Assert.Equal(goodId, result.First().Id);
        }

        [Fact]
        public async Task SearchCount_returns_correct_count()
        {
            var items = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Alice", SomeNumber = 1 },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Alice", SomeNumber = 2 },
                new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Bob",   SomeNumber = 3 },
            };
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, items);

            var count = await Sut.SearchCount(new[]
            {
                SearchTerm<TableWithNoAutoGeneratedPrimaryKey>.Create(x => x.NameTest, "Alice", SearchType.Equals)
            });

            Assert.Equal(2, count);
        }
    }
}
