using System;
using System.Linq;
using System.Threading.Tasks;
using Mkb.DapperRepo.Search;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using Xunit;

namespace Mkb.DapperRepo.Tests.Tests.Repo.Search
{
    [Collection("Integration")]
    public class SearchAsyncTests : BaseAsyncTestClass
    {
        [Fact]
        public async Task Ensure_we_can_match_null()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = null }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search(
                new TableWithNoAutoGeneratedPrimaryKey { NameTest = "Michael", SomeNumber = null },
                new[]
                {
                    SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.NameTest), SearchType.Equals),
                    SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.SomeNumber), SearchType.IsNull)
                });

            Assert.Single(result);
        }

        [Fact]
        public async Task Ensure_we_can_match_exact()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "chaal", SomeNumber = 73 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1 }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search(new TableWithNoAutoGeneratedPrimaryKey { NameTest = "Michael" },
                SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.NameTest) , SearchType.Equals));

            Assert.Single(result);
        }

        [Fact]
        public async Task Ensure_we_ignore_case_on_property()
        {
            if (DapperRepo.Tests.Connection.SelectedEnvironment == Enviroment.PostgreSQL)
            {
                // postgres is case-sensitive this will fail
                return;
            }

            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "chaal", SomeNumber = 73 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1 }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search<TableWithNoAutoGeneratedPrimaryKey>("NameTest", "Michael");

            Assert.Single(result);
        }

        [Fact]
        public async Task Ensure_we_can_match_like_ignoring_first_chars()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "chael", SomeNumber = 73 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1 }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result =
                await Sut.Search<TableWithNoAutoGeneratedPrimaryKey>(
                    nameof(TableWithNoAutoGeneratedPrimaryKey.NameTest), "%chael");

            Assert.Equal(2, result.Count());
        }

        [Fact]
        public async Task Ensure_we_can_match_on_numbers()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "chael", SomeNumber = 73 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1 }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result =
                await Sut.Search<TableWithNoAutoGeneratedPrimaryKey, int?>(
                    nameof(TableWithNoAutoGeneratedPrimaryKey.SomeNumber), 33, SearchType.Equals);

            Assert.Single(result);
        }

        [Fact]
        public async Task Ensure_we_can_match_like_ignoring_end()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "chael", SomeNumber = 73 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1 }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result =
                await Sut.Search<TableWithNoAutoGeneratedPrimaryKey>(
                    nameof(TableWithNoAutoGeneratedPrimaryKey.NameTest), "%cha%");

            Assert.Equal(3, result.Count());
        }

        [Fact]
        public async Task Ensure_we_can_match_on_GreaterThan()
        {
            var goodId = Guid.NewGuid().ToString("N");
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33, },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13, },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = goodId, NameTest = "chael", SomeNumber = 73, },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 1, }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search(new TableWithNoAutoGeneratedPrimaryKey
            {
                SomeNumber = 63
            }, SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.SomeNumber), SearchType.GreaterThan));

            var tableWithNoAutoGeneratedPrimaryKeys = result as TableWithNoAutoGeneratedPrimaryKey[] ?? result.ToArray();
            Assert.Single(tableWithNoAutoGeneratedPrimaryKeys);
            Assert.Equal(goodId, tableWithNoAutoGeneratedPrimaryKeys.First().Id);
        }

        [Fact]
        public async Task Ensure_we_can_match_on_GreaterThanEqual()
        {
            var goodId = Guid.NewGuid().ToString("N");
            var goodId2 = Guid.NewGuid().ToString("N");
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33, },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13, },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = goodId, NameTest = "chael", SomeNumber = 51 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = goodId2, NameTest = "othername", SomeNumber = 91, }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search(new TableWithNoAutoGeneratedPrimaryKey
            {
                SomeNumber = 51
            }, SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.SomeNumber), SearchType.GreaterThanEqualTo));

            var tableWithNoAutoGeneratedPrimaryKeys = result as TableWithNoAutoGeneratedPrimaryKey[] ?? result.ToArray();
            Assert.Equal(2, tableWithNoAutoGeneratedPrimaryKeys.Count());
            Assert.Contains(goodId, tableWithNoAutoGeneratedPrimaryKeys.Select(t => t.Id).ToArray());
            Assert.Contains(goodId2, tableWithNoAutoGeneratedPrimaryKeys.Select(t => t.Id).ToArray());
        }

        [Fact]
        public async Task Ensure_we_can_match_on_LessThan()
        {
            var goodId = Guid.NewGuid().ToString("N");
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33, },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13, },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = goodId, NameTest = "chael", SomeNumber = 5 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 15, }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search(new TableWithNoAutoGeneratedPrimaryKey
            {
                SomeNumber = 9
            }, SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.SomeNumber), SearchType.LessThan));

            var tableWithNoAutoGeneratedPrimaryKeys = result as TableWithNoAutoGeneratedPrimaryKey[] ?? result.ToArray();
            Assert.Single(tableWithNoAutoGeneratedPrimaryKeys);
            Assert.Equal(goodId, tableWithNoAutoGeneratedPrimaryKeys.First().Id);
        }

        [Fact]
        public async Task Ensure_we_can_match_on_LessThanEqual()
        {
            var goodId = Guid.NewGuid().ToString("N");
            var goodId2 = Guid.NewGuid().ToString("N");
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = goodId, NameTest = "chael", SomeNumber = 5 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = goodId2, NameTest = "othername", SomeNumber = 9 }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search(new TableWithNoAutoGeneratedPrimaryKey
            {
                SomeNumber = 9
            },SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.SomeNumber), SearchType.LessThanEqualTo));

            TableWithNoAutoGeneratedPrimaryKey[] tableWithNoAutoGeneratedPrimaryKeys = result as TableWithNoAutoGeneratedPrimaryKey[] ?? result.ToArray();
            Assert.Equal(2, tableWithNoAutoGeneratedPrimaryKeys.Length);
            Assert.Contains(goodId, tableWithNoAutoGeneratedPrimaryKeys.Select(t => t.Id).ToArray());
            Assert.Contains(goodId2, tableWithNoAutoGeneratedPrimaryKeys.Select(t => t.Id).ToArray());
        }

        [Fact]
        public async Task Ensure_we_can_match_on_multiple()
        {
            var goodId = Guid.NewGuid().ToString("N");
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "Michael", SomeNumber = 13 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = goodId, NameTest = "chael", SomeNumber = 8 },
                new TableWithNoAutoGeneratedPrimaryKey
                    { Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 8 }
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var result = await Sut.Search(new TableWithNoAutoGeneratedPrimaryKey
            {
                NameTest = "%hae%",
                SomeNumber = 9
            }, new[]
            {
               SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.SomeNumber), SearchType.LessThanEqualTo), 
               SearchCriteria.Create(nameof(TableWithNoAutoGeneratedPrimaryKey.NameTest), SearchType.Like)
            });

            var tableWithNoAutoGeneratedPrimaryKeys = result as TableWithNoAutoGeneratedPrimaryKey[] ?? result.ToArray();
            Assert.Single(tableWithNoAutoGeneratedPrimaryKeys);
            Assert.Contains(goodId, tableWithNoAutoGeneratedPrimaryKeys.Select(t => t.Id).ToArray());
        }

        [Fact]
        public async Task Ensure_we_throw_error_if_property_is_not_a_string()
        {
            var exception = await Assert.ThrowsAsync<Exception>(async () =>
                await Sut.Search<TableWithNoAutoGeneratedPrimaryKey>("SomeNumber", "%cha%"));

            Assert.Contains("Type Must Be String", exception.Message);
        }

        [Fact]
        public async Task Ensure_we_throw_error_if_property_is_not_found()
        {
            var exception = await Assert.ThrowsAsync<Exception>(async () =>
                await Sut.Search<TableWithNoAutoGeneratedPrimaryKey>("ge", "%cha%"));

            Assert.Contains("not found in Type:", exception.Message);
        }
    }
}