using System;
using System.Linq;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using NUnit.Framework;

namespace Mkb.DapperRepo.Tests.Tests.Repo.Delete
{
    public class DeleteTests : BaseSyncTestClass
    {
        [Test]
        public void Ensure_we_can_Delete_a_record()
        {
            var testTableItem = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), Name = "Michale", SomeNumber = 33};
            var dontTouch = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), Name = "gwgw", SomeNumber = 12};
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, new[] {testTableItem, dontTouch});
            Sut.Delete(testTableItem);

            var records = DataBaseScriptRunnerAndBuilder.GetAll<TableWithNoAutoGeneratedPrimaryKey>(Connection).ToArray();

            Assert.AreEqual(1, records.Count());
            Assert.AreEqual(dontTouch.Id, records.First().Id);
            Assert.AreEqual(dontTouch.SomeNumber, records.First().SomeNumber);
            Assert.AreEqual(dontTouch.Name, records.First().Name);
        }
        
        [Test]
        public void  Ensure_we_can_Delete_a_record_diff_name()
        {
            var testTableItem = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), Name = "Michale", SomeNumber = 33};
            var dontTouch = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), Name = "gwgw", SomeNumber = 12};
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, new[] {testTableItem, dontTouch});
            Sut.Delete(new TableWithNoAutoGeneratedPrimaryKeyDiffSqlName(testTableItem));

            var records = DataBaseScriptRunnerAndBuilder.GetAll<TableWithNoAutoGeneratedPrimaryKey>(Connection).ToArray();
            Assert.AreEqual(1, records.Count());
            Assert.AreEqual(dontTouch.Id, records.First().Id);
            Assert.AreEqual(dontTouch.SomeNumber, records.First().SomeNumber);
            Assert.AreEqual(dontTouch.Name, records.First().Name);
        }
    }
}