using System;
using System.Linq;
using Mkb.DapperRepo.Exceptions;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using NUnit.Framework;

namespace Mkb.DapperRepo.Tests.Tests.Repo.Delete
{
    public class DeleteTests : BaseSyncTestClass
    {
        [Test]
        public void Ensure_we_cant_update_if_class_missing_priamarKey()
        {
            var exception =
                Assert.Throws<PrimaryKeyNotFoundException>( () =>
                    Sut.Update(new SqlTableNoPrimaryKeyAttribute()));
            Assert.AreEqual($"Primary key not found on table:{nameof(SqlTableNoPrimaryKeyAttribute)}",
                exception.Message);
        }
        
        [Test]
        public void Ensure_we_can_Delete_a_record()
        {
            var testTableItem = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33};
            var dontTouch = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "gwgw", SomeNumber = 12};
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, new[] {testTableItem, dontTouch});
            Sut.Delete(testTableItem);

            var records = DataBaseScriptRunnerAndBuilder.GetAll<TableWithNoAutoGeneratedPrimaryKey>(Connection).ToArray();

            Assert.AreEqual(1, records.Count());
            Assert.AreEqual(dontTouch.Id, records.First().Id);
            Assert.AreEqual(dontTouch.SomeNumber, records.First().SomeNumber);
            Assert.AreEqual(dontTouch.NameTest, records.First().NameTest);
        }
        
        [Test]
        public void  Ensure_we_can_Delete_a_record_diff_name()
        {
            var testTableItem = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33};
            var dontTouch = new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "gwgw", SomeNumber = 12};
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, new[] {testTableItem, dontTouch});
            Sut.Delete(new TableWithNoAutoGeneratedPrimaryKeyDiffSqlName(testTableItem));

            var records = DataBaseScriptRunnerAndBuilder.GetAll<TableWithNoAutoGeneratedPrimaryKey>(Connection).ToArray();
            Assert.AreEqual(1, records.Count());
            Assert.AreEqual(dontTouch.Id, records.First().Id);
            Assert.AreEqual(dontTouch.SomeNumber, records.First().SomeNumber);
            Assert.AreEqual(dontTouch.NameTest, records.First().NameTest);
        }
    }
}