using System;
using System.Linq;
using System.Threading.Tasks;
using Mkb.DapperRepo.Exceptions;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using Xunit;

namespace Mkb.DapperRepo.Tests.Tests.Repo.Delete
{
    [Collection("Integration")]
    public class DeleteAsyncTest : BaseAsyncTestClass
    {
        [Fact]
        public async Task Ensure_we_cant_update_if_class_missing_priamarKey()
        {
            var exception = await
                Assert.ThrowsAsync<PrimaryKeyNotFoundException>(async () =>
                    await Sut.Delete(new SqlTableNoPrimaryKeyAttribute()));
            Assert.Equal($"Primary key not found on table:{nameof(SqlTableNoPrimaryKeyAttribute)}",
                exception.Message);
        }

        [Fact]
        public async Task Ensure_we_can_Delete_a_record()
        {
            var testTableItem = new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 };
            var dontTouch = new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "gwgw", SomeNumber = 12 };
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, new[] { testTableItem, dontTouch });
            await Sut.Delete(testTableItem);

            var records = DataBaseScriptRunnerAndBuilder.GetAll<TableWithNoAutoGeneratedPrimaryKey>(Connection).ToArray();
            Assert.Single(records);
            Assert.Equal(dontTouch.Id, records.First().Id);
            Assert.Equal(dontTouch.SomeNumber, records.First().SomeNumber);
            Assert.Equal(dontTouch.NameTest, records.First().NameTest);
        }

        [Fact]
        public async Task Ensure_we_can_Delete_a_record_diff_name()
        {
            var testTableItem = new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "Michale", SomeNumber = 33 };
            var dontTouch = new TableWithNoAutoGeneratedPrimaryKey { Id = Guid.NewGuid().ToString("N"), NameTest = "gwgw", SomeNumber = 12 };
            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, new[] { testTableItem, dontTouch });
            await Sut.Delete(new TableWithNoAutoGeneratedPrimaryKeyDiffSqlName(testTableItem));

            var records = DataBaseScriptRunnerAndBuilder.GetAll<TableWithNoAutoGeneratedPrimaryKey>(Connection).ToArray();
            Assert.Single(records);
            Assert.Equal(dontTouch.Id, records.First().Id);
            Assert.Equal(dontTouch.SomeNumber, records.First().SomeNumber);
            Assert.Equal(dontTouch.NameTest, records.First().NameTest);
        }
    }
}