using System;
using System.Linq;
using System.Threading.Tasks;
using Mkb.DapperRepo.Tests.Entities;
using Mkb.DapperRepo.Tests.Tests.BaseTestClasses;
using Mkb.DapperRepo.Tests.Utils;
using NUnit.Framework;

namespace Mkb.DapperRepo.Tests.Tests.Repo.QuerySingle
{
    public class QuerySingleAsyncTests : BaseAsyncTestClass
    {
       [TestCase("name")]
       [TestCase("NaMe")]
       [TestCase("NameTest")]
       [TestCase("nametest")]
        public async Task Ensure_we_Get_correct_record_back_with_both_mappings_and_ignore_case(string fieldName)
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Wanted1", SomeNumber = 11},
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 33},
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Wanted2", SomeNumber = 21}
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var item = (await Sut.QuerySingle<TableWithNoAutoGeneratedPrimaryKey>(
                "select id,name as name,somenumber from TableWithNoAutoGeneratedPrimaryKey where SomeNumber = 33"));
            var expected = testTableItems.First(f => f.SomeNumber == 33);


            Assert.IsNotNull(item);
            Assert.AreEqual(item.NameTest, expected.NameTest);
            Assert.AreEqual(item.Id, expected.Id);
            Assert.AreEqual(item.SomeNumber, expected.SomeNumber);
        }
        
        [Test]
        public async Task Ensure_we_Get_correct_record_back_with_diff_name()
        {
            var testTableItems = new[]
            {
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Wanted1", SomeNumber = 11},
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "othername", SomeNumber = 33},
                new TableWithNoAutoGeneratedPrimaryKey {Id = Guid.NewGuid().ToString("N"), NameTest = "Wanted2", SomeNumber = 21}
            };

            DataBaseScriptRunnerAndBuilder.InsertTableWithNoAutoGeneratedPrimaryKey(Connection, testTableItems);

            var item = (await Sut.QuerySingle<TableWithNoAutoGeneratedPrimaryKeyDiffSqlName>(
                "select * from TableWithNoAutoGeneratedPrimaryKey where SomeNumber = 33"));
            var expected = testTableItems.First(f => f.SomeNumber == 33);


            Assert.IsNotNull(item);
            Assert.AreEqual(item.Name, expected.NameTest);
            Assert.AreEqual(item.Id, expected.Id);
            Assert.AreEqual(item.SomeNumber, expected.SomeNumber);
        }

        [Test]
        public async Task Ensure_if_we_have_no_records_we_do_not_blow_up()
        {
            var item = (await Sut.QuerySingle<TableWithNoAutoGeneratedPrimaryKey>(
                "select * from TableWithNoAutoGeneratedPrimaryKey"));
            Assert.IsNull(item);
        }
    }
}