using System;
using Mkb.DapperRepo.Attributes;

namespace Mkb.DapperRepo.Tests.Entities
{
    public class TableWithNoAutoGeneratedPrimaryKey
    {
        [PrimaryKey]
        public Guid Id { get; set; }

        public string Name { get; set; }
        public int? SomeNumber { get; set; }
    }
    

        // This is a copy of TableWithAutIncrementPrimaryKey but with different names and sql name makes them the same for testing
        // this is to test SqlName
}